[GLOBAL]
pants_version = "2.18.0"

backend_packages.add = [
    "pants.backend.python",
    "pants.backend.docker",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
]

[python]
interpreter_constraints = ["CPython~=3.10.12"]

[python-bootstrap]
search_path = ["<PYENV>", "/usr/bin"]

[python-infer]
imports = false

[source]
marker_filenames = ["BUILD.pants"]

[test]
output = "failed"
