name: tests

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/tests.yml
      - auto_super_six/**
      - tests/**
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/tests.yml
      - auto_super_six/**
      - tests/**

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache0-py${{ matrix.python_version }}
        named-caches-hash: ${{ hashFiles('lockfiles/*.json', '**/something-else.lock') }}

    - name: Test `auto_super_six` lib
      run: |
        pants test auto_super_six::
